// src/components/ui/progress-button.tsx
import {Button} from "@/components/ui/button.tsx";
import {useMemo} from "react";

interface ProgressButtonProps {
    children: React.ReactNode
    progress: number
    onClick: () => void
}

function ProgressButton ({
    children,
    ...props
}: ProgressButtonProps) {
    const backgroundStyle = useMemo(() => {
        return {
            width: `${props.progress}%`
        }
    }, [props.progress])

    return (
        <div className='w-full relative'>
            <div className='h-full rounded-md bg-lime-700 absolute' style={backgroundStyle} />
            <div className='w-full rounded-md p-1 relative'>
                <Button className="w-full" variant='ghost' onClick={props.onClick}>
                    {children}
                </Button>
            </div>
        </div>)
}

export default ProgressButton

// src/shared/ui/ProgressButton.vue
<script setup lang="ts">

import { Button} from "@/shared/ui/button";
import {computed} from "vue";

const props = defineProps<{
    onClick: () => void
    progress: number
}>()

const backgroundStyle = computed<{ width: string }>(() => {
    return {
        width: `${props.progress}%`
    }
})
</script>

<template>
    <div class='w-full relative'>
        <div
            class='h-full rounded-md bg-lime-700 absolute'
            :style="backgroundStyle"
        />
        <div class='w-full rounded-md p-1 relative'>
            <Button
                class='w-full'
                variant='ghost'
                @click="props.onClick"
            >
                <slot />
            </Button>
        </div>
    </div>
</template>

<style scoped>

</style>
