// src/modules/Village/village.tsx
import { Separator } from '@/components/ui/separator.tsx';
import BuildingsRecipes from '@/constants/buildings-recipes.ts';
import { display } from '@/lib/numbers.ts';
import CraftBuild from '@/modules/Village/components/craft-build.tsx';
import { useBoundStore } from '@/store/store.ts';

function Village() {
    const boundStore = useBoundStore();

    return (
        <div className='flex flex-col w-full h-full gap-2 p-2'>
            <div>
                <span className='text-xl'>
                    {display(boundStore.villagers)} villager
                </span>
            </div>
            <Separator />
            <div className='grid grid-cols-2 gap-2 w-full'>
                <CraftBuild buildingRecipe={BuildingsRecipes.OAK_HOUSE} />
            </div>
        </div>
    );
}

export default Village;

// src/modules/Village/Village.vue
<script setup lang="ts">
import CraftBuild from '@/modules/Village/components/CraftBuild.vue';
import { useVillageStore } from '@/modules/Village/store/village.store';
import BuildingsRecipes from '@/shared/constants/buildings-recipes';
import { Separator } from '@/shared/ui/separator';
import { display } from '@/utils/numbers';

const villageStore = useVillageStore();
</script>

<template>
    <div class="flex flex-col w-full h-full gap-2 p-2">
        <div>
            <span class="text-xl">
                {{ display(villageStore.villagers) }} villager
            </span>
        </div>
        <Separator />
        <div class="grid grid-cols-2 gap-2 w-full">
            <CraftBuild :buildingRecipe="BuildingsRecipes.OAK_HOUSE" />
        </div>
    </div>
</template>

<style scoped></style>
