// src/modules/MainLayout/components/sidebar.tsx
import { Button } from '@/components/ui/button.tsx';
import Sections from '@/modules/MainLayout/constants/sections.ts';

type SidebarProps = {
    setSection: (section: Sections) => void;
};

function Sidebar({ ...props }: SidebarProps) {
    return (
        <div className='flex flex-col w-64 flex-none m-2 gap-2'>
            <Button
                className='w-full'
                onClick={() => props.setSection(Sections.FOREST)}
            >
                Forest
            </Button>
            <Button
                className='w-full'
                onClick={() => props.setSection(Sections.MINE)}
            >
                Mine
            </Button>
            <Button
                className='w-full'
                onClick={() => props.setSection(Sections.CRAFT)}
            >
                Craft
            </Button>
            <Button
                className='w-full'
                onClick={() => props.setSection(Sections.VILLAGE)}
            >
                Village
            </Button>
        </div>
    );
}

export default Sidebar;

// src/modules/Sidebar/Sidebar.vue
<script setup lang="ts">
import Sections from '@/shared/models/sections';
import { Button } from '@/shared/ui/button';

const props = defineProps<{
    setSection: (section: Sections) => void;
}>();
</script>

<template>
    <div class="flex flex-col w-64 flex-none m-2 gap-2">
        <Button
            class="w-full"
            @click="() => props.setSection(Sections.FOREST)"
        >
            Forest
        </Button>
        <Button
            class="w-full"
            @click="() => props.setSection(Sections.MINE)"
        >
            Mine
        </Button>
        <Button
            class="w-full"
            @click="() => props.setSection(Sections.CRAFT)"
        >
            Craft
        </Button>
        <Button
            class="w-full"
            @click="() => props.setSection(Sections.VILLAGE)"
        >
            Village
        </Button>
    </div>
</template>

<style scoped></style>
