// src/modules/Inventory/components/building-cell.tsx
import { Card } from '@/components/ui/card.tsx';
import { display } from '@/lib/numbers.ts';
import { VillageBuilding } from '@/types/village-types.ts';
import { useMemo } from 'react';

function BuildingCell(props: { building: VillageBuilding }) {
    const perSecond = useMemo(() => {
        return props.building.perSecond
            ? `${display(props.building.perSecond)} /s`
            : '';
    }, [props.building.perSecond]);

    return (
        <Card className='flex justify-between h-16 w-full overflow-clip relative gap-1 p-2'>
            <div className='flex flex-row justify-between items-center w-full h-full'>
                <span className='text-lg text-stone-50'>
                    {props.building.building.displayName}
                </span>
                <span className='text-sm text-stone-500'>
                    {display(props.building.quantity)}
                </span>
                <span className='text-xs text-stone-500'>{perSecond}</span>
            </div>
        </Card>
    );
}

export default BuildingCell;

// src/modules/Inventory/components/BuildingCell.vue
<script setup lang="ts">

import {Card} from "@/shared/ui/card";
import {display} from "@/lib/numbers";
import type {VillageBuilding} from "@/shared/models/villageTypes";

const props = defineProps<{
    building: VillageBuilding;
}>();

</script>

<template>
    <Card class='flex justify-between h-16 w-full overflow-clip relative gap-1 p-2'>
        <div class='flex flex-row justify-between items-center w-full h-full'>
                <span class='text-lg text-stone-50'>
                    {{ props.building.building.displayName }}
                </span>
            <span class='text-sm text-stone-500'>
                    {{ display(props.building.quantity) }}
                </span>
            <span class='text-xs text-stone-500'>{perSecond}</span>
        </div>
    </Card>
</template>

<style scoped>

</style>
