// src/modules/DevTools/devtools.tsx
import {
    Popover,
    PopoverContent,
    PopoverTrigger,
} from '@/components/ui/popover.tsx';
import { Button } from '@/components/ui/button.tsx';
import { useTick } from '@/components/providers/tick-provider.tsx';
import { useMemo, useState } from 'react';

function Devtools() {
    const [lastTickDuration, setLastTickDuration] = useState<number>(0);

    const fps = useMemo(() => {
        return Math.floor(1000 / lastTickDuration);
    }, [lastTickDuration]);

    useTick((elapsedTime: number) => {
        setLastTickDuration(elapsedTime);
    });

    return (
        <div className='pl-2'>
            <Popover>
                <PopoverTrigger asChild>
                    <Button
                        variant='outline'
                        className='text-red-500'
                    >
                        DEV
                    </Button>
                </PopoverTrigger>
                <PopoverContent className='w-96'>
                    <p>FPS: {fps}</p>
                </PopoverContent>
            </Popover>
        </div>
    );
}

export default Devtools;

// src/modules/Devtools/Devtools.vue
<script setup lang="ts">
import { useTickStore } from '@/shared/stores/tick.store';
import { Button } from '@/shared/ui/button';
import { Popover, PopoverContent, PopoverTrigger } from '@/shared/ui/popover';
import { computed, ref } from 'vue';

const tickStore = useTickStore();

const lastTickDuration = ref<number>(0);

const fps = computed(() => {
    return Math.floor(1000 / lastTickDuration.value);
});

tickStore.addTickFunction((elapsedTime: number) => {
    lastTickDuration.value = elapsedTime;
});
</script>

<template>
    <div class="pl-2">
        <Popover>
            <PopoverTrigger asChild>
                <Button
                    variant="outline"
                    class="text-red-500"
                >
                    DEV
                </Button>
            </PopoverTrigger>
            <PopoverContent class="w-96">
                <p>FPS: {{ fps }}</p>
            </PopoverContent>
        </Popover>
    </div>
</template>

<style scoped></style>
