// src/views/main/components/MainCard.vue
<script setup lang="ts">
import Craft from '@/modules/Craft/Craft.vue';
import Forest from '@/modules/Forest/Forest.vue';
import Mine from '@/modules/Mine/Mine.vue';
import Village from '@/modules/Village/Village.vue';
import Sections from '@/shared/models/sections';
import { Card } from '@/shared/ui/card';

const props = defineProps<{
    section: Sections;
}>();
</script>

<template>
    <div class="flex flex-auto m-2">
        <Card class="flex flex-auto">
            <Forest v-if="props.section === Sections.FOREST" />
            <Mine v-if="props.section === Sections.MINE" />
            <Craft v-if="props.section === Sections.CRAFT" />
            <Village v-if="props.section === Sections.VILLAGE" />
        </Card>
    </div>
</template>

<style scoped></style>

// src/modules/MainLayout/components/main-card.tsx
import { Card } from '@/components/ui/card.tsx';
import Craft from '@/modules/Craft/craft.tsx';
import Forest from '@/modules/Forest/forest.tsx';
import Sections from '@/modules/MainLayout/constants/sections.ts';
import Mine from '@/modules/Mine/mine.tsx';
import Village from '@/modules/Village/village.tsx';

type MainCardProps = {
    section: Sections;
};

function MainCard({ ...props }: MainCardProps) {
    const sectionToDisplay = () => {
        switch (props.section) {
            case Sections.FOREST:
                return <Forest />;
            case Sections.VILLAGE:
                return <Village />;
            case Sections.CRAFT:
                return <Craft />;
            case Sections.MINE:
                return <Mine />;
            default:
                return <></>;
        }
    };

    return (
        <div className='flex flex-auto m-2'>
            <Card className='flex flex-auto'>{sectionToDisplay()}</Card>
        </div>
    );
}

export default MainCard;
