// src/modules/StatusBar/StatusBar.vue
<script setup lang="ts">

import Devtools from "@/modules/Devtools/Devtools.vue";
import ToggleTheme from "@/modules/StatusBar/components/ToggleTheme.vue";
import { Separator } from "@/shared/ui/separator";

</script>

<template>
    <div class='flex flex-row justify-between w-full p-2'>
        <div>
            <ToggleTheme />
        </div>
        <div class='flex flex-row'>
            <Separator orientation='vertical' />
            <Devtools />
        </div>
    </div>
</template>

<style scoped>

</style>

// src/modules/MainLayout/components/status-bar.tsx
import {ThemeToggle} from "@/components/theme-toggle.tsx";
import {Separator} from "@/components/ui/separator.tsx";
import Devtools from "@/modules/DevTools/devtools.tsx";

function StatusBar() {
    return (
        <div className="flex flex-row justify-between w-full p-2">
            <div>
                <ThemeToggle/>
            </div>
            <div className="flex flex-row">
                <Separator orientation="vertical"/>
                <Devtools/>
            </div>
        </div>
    )
}

export default StatusBar
