// src/modules/Forest/forest.tsx
import { Separator } from '@/components/ui/separator.tsx';
import Chop from '@/modules/Forest/components/chop.tsx';

function Forest() {
    return (
        <div className='flex flex-col p-2 gap-2 w-full h-full'>
            <Chop />
            <Separator />
        </div>
    );
}

export default Forest;

// src/modules/Forest/Forest.vue
<script setup lang="ts">
import Chop from '@/modules/Forest/components/Chop.vue';
import { UiSeparator } from '@/shared/ui/separator';
</script>

<template>
    <div class="flex flex-col p-2 gap-2 w-full h-full">
        <Chop />
        <UiSeparator />
    </div>
</template>

<style scoped></style>
